
/* Auto generated by Glue Client Compiler tool (gluec)
on 17.05.2017 19:11:47 at CRAZYROGUE by mad
Do not modify this file by hand if you plan to regenerate this file again by the tool as manual changes will be lost
*/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.IO;

using NFX.Glue;
using NFX.Glue.Protocol;


namespace Test002.Contracts.Servicies.GluedClients
{
  ///<summary>
  /// Client for glued contract Test002.Contracts.Servicies.ITestMessage server.
  /// Each contract method has synchronous and asynchronous versions, the later denoted by 'Async_' prefix.
  /// May inject client-level inspectors here like so:
  ///   client.MsgInspectors.Register( new YOUR_CLIENT_INSPECTOR_TYPE());
  ///</summary>
  public class TestMessageAutoClient : ClientEndPoint, @Test002.@Contracts.@Servicies.@ITestMessage
  {

  #region Static Members

     private static TypeSpec s_ts_CONTRACT;
     private static MethodSpec @s_ms_send_0;
     private static MethodSpec @s_ms_recive_1;

     //static .ctor
     static TestMessageAutoClient()
     {
         var t = typeof(@Test002.@Contracts.@Servicies.@ITestMessage);
         s_ts_CONTRACT = new TypeSpec(t);
         @s_ms_send_0 = new MethodSpec(t.GetMethod("send", new Type[]{ typeof(@Test002.@Contracts.@TestMessage) }));
         @s_ms_recive_1 = new MethodSpec(t.GetMethod("recive", new Type[]{ typeof(@System.@String) }));
     }
  #endregion

  #region .ctor
     public TestMessageAutoClient(string node, Binding binding = null) : base(node, binding) { ctor(); }
     public TestMessageAutoClient(Node node, Binding binding = null) : base(node, binding) { ctor(); }
     public TestMessageAutoClient(IGlue glue, string node, Binding binding = null) : base(glue, node, binding) { ctor(); }
     public TestMessageAutoClient(IGlue glue, Node node, Binding binding = null) : base(glue, node, binding) { ctor(); }

     //common instance .ctor body
     private void ctor()
     {

     }

  #endregion

     public override Type Contract
     {
       get { return typeof(@Test002.@Contracts.@Servicies.@ITestMessage); }
     }



  #region Contract Methods

         ///<summary>
         /// Synchronous invoker for  'Test002.Contracts.Servicies.ITestMessage.send'.
         /// This is a two-way call per contract specification, meaning - the server sends the result back either
         ///  returning no exception or WrappedExceptionData instance.
         /// ClientCallException is thrown if the call could not be placed in the outgoing queue.
         /// RemoteException is thrown if the server generated exception during method execution.
         ///</summary>
         public void @send(@Test002.@Contracts.@TestMessage  @message)
         {
            var call = Async_send(@message);
            call.CheckVoidValue();
         }

         ///<summary>
         /// Asynchronous invoker for  'Test002.Contracts.Servicies.ITestMessage.send'.
         /// This is a two-way call per contract specification, meaning - the server sends the result back either
         ///  returning no exception or WrappedExceptionData instance.
         /// CallSlot is returned that can be queried for CallStatus, ResponseMsg and result.
         ///</summary>
         public CallSlot Async_send(@Test002.@Contracts.@TestMessage  @message)
         {
            var request = new RequestAnyMsg(s_ts_CONTRACT, @s_ms_send_0, false, RemoteInstance, new object[]{@message});
            return DispatchCall(request);
         }



         ///<summary>
         /// Synchronous invoker for  'Test002.Contracts.Servicies.ITestMessage.recive'.
         /// This is a two-way call per contract specification, meaning - the server sends the result back either
         ///  returning '@Test002.@Contracts.@TestMessage' or WrappedExceptionData instance.
         /// ClientCallException is thrown if the call could not be placed in the outgoing queue.
         /// RemoteException is thrown if the server generated exception during method execution.
         ///</summary>
         public @Test002.@Contracts.@TestMessage @recive(@System.@String  @reciever)
         {
            var call = Async_recive(@reciever);
            return call.GetValue<@Test002.@Contracts.@TestMessage>();
         }

         ///<summary>
         /// Asynchronous invoker for  'Test002.Contracts.Servicies.ITestMessage.recive'.
         /// This is a two-way call per contract specification, meaning - the server sends the result back either
         ///  returning no exception or WrappedExceptionData instance.
         /// CallSlot is returned that can be queried for CallStatus, ResponseMsg and result.
         ///</summary>
         public CallSlot Async_recive(@System.@String  @reciever)
         {
            var request = new RequestAnyMsg(s_ts_CONTRACT, @s_ms_recive_1, false, RemoteInstance, new object[]{@reciever});
            return DispatchCall(request);
         }


  #endregion

  }//class
}//namespace
